import 'package:flutter/material.dart';

const String rootRoute = '/';
const String mainRoute = '/main';
const String loginRoute = '/login';
const String dashboardRoute = '/dashboard';
const String dashboardduaRoute = '/dashboarddua';
const String kwitansiRoute = '/kwitansi';
const String notifikasiRoute = '/notifikasi';
const String pengumumanRoute = '/pengumuman';
const String persyaratanRoute = '/persyaratan';
const String isiformulirRoute = '/isiformulir';
const String metodepembayaranRoute = '/metodepembayaran';
// const String metodepembayaranRoute = '/totalpembayaran';
const String pembayaranRoute = '/pembayaran';
const String profilpondokRoute = '/profilpondok';
const String profilsekolahRoute = '/profilsekolah';
const String mtsRoute = '/mts';
const String maRoute = '/ma';
const String datapribadiRoute = '/datapribadi';
